In [ ]:
# Traditional Python list
temps_list = [72, 75, 68, 71, 74, 69, 73]
# Convert to NumPy array
import numpy as np
temps_array = np.array([72, 75, 68, 71, 74, 69, 73])
print(temps_array)



[72 75 68 71 74 69 73]


In [ ]:
# Temperatures from 3 sensors over 5 days
sensor_temps = np.array([
 [72, 70, 71], # Day 1
 [75, 73, 74], # Day 2
 [68, 67, 69], # Day 3
 [71, 70, 72], # Day 4
 [74, 72, 73] # Day 5
])
print(sensor_temps)
print(f"Shape: {sensor_temps.shape}")

[[72 70 71]
 [75 73 74]
 [68 67 69]
 [71 70 72]
 [74 72 73]]
Shape: (5, 3)


In [2]:
import numpy as np
# Temperatures from 3 sensors over 5 days
sensor_temps = np.array([
 [72, 70, 71], # Day 1
 [75, 73, 74], # Day 2
 [68, 67, 69], # Day 3
 [71, 70, 72], # Day 4
 [74, 72, 73] # Day 5
])
print(sensor_temps)
print(f"Shape: {sensor_temps.shape}")
# Output: Shape: (5, 3)
# 5 rows (days), 3 columns (sensors)

[[72 70 71]
 [75 73 74]
 [68 67 69]
 [71 70 72]
 [74 72 73]]
Shape: (5, 3)


In [3]:
crops = np.array(['corn', 'wheat', 'soy', 'barley', 'oats'])
# Access single element (zero-indexed)
print(crops[0]) # Output: 'corn'
print(crops[-1]) # Output: 'oats' (negative indexing from end)
# Access multiple elements
print(crops[1:4]) # Output: ['wheat' 'soy' 'barley'] (slice from index 1 to 3)
print(crops[::2]) # Output: ['corn' 'soy' 'oats'] (every 2nd element)

corn
oats
['wheat' 'soy' 'barley']
['corn' 'soy' 'oats']


In [4]:
# Soil pH readings (3 fields × 4 samples)
ph_levels = np.array([
 [6.5, 6.8, 6.3, 6.7],
 [7.1, 7.0, 6.9, 7.2],
 [6.2, 6.4, 6.1, 6.3]
])
# Single element: row 1, column 2
print(ph_levels[1, 2]) # Output: 6.9
# Entire row 0
print(ph_levels[0, :])
# Output: [6.5 6.8 6.3 6.7]
# Entire column 3
print(ph_levels[:, 3])


6.9
[6.5 6.8 6.3 6.7]
[6.7 7.2 6.3]


In [5]:
# Crop yields in tons
field_a = np.array([120, 135, 142, 128])
field_b = np.array([118, 140, 138, 132])
# Add arrays
total_yield = field_a + field_b
print(total_yield)
# Output: [238 275 280 260]
# Subtract to find difference
difference = field_a - field_b
print(difference)
# Output: [2 -5 4 -4]
# Multiply each by a constant
doubled = field_a * 2
print(doubled)

[238 275 280 260]
[ 2 -5  4 -4]
[240 270 284 256]
