In [1]:

import numpy as np

# === MATRIX CREATION ===
print("=== Matrix Creation ===")

# Farm data: 3 plots, 4 factors each
# Columns: temp, rain, pH, fertilizer
farm_factors = np.array([
    [28, 150, 6.5, 50],
    [30, 120, 6.8, 45],
    [26, 180, 6.2, 60]
])
print(f"Farm Factors (3x4):\n{farm_factors}")

# Weights for yield prediction
weights = np.array([[10], [5], [100], [20]])  # 4x1
print(f"\nWeights (4x1):\n{weights.flatten()}")

# === MATRIX MULTIPLICATION ===
print("\n=== Matrix Multiplication ===")

# Predicted yields = factors @ weights + base
base_yield = 1000
predicted_yields = farm_factors @ weights + base_yield
print(f"Predicted Yields:\n{predicted_yields.flatten()}")

# === TRANSPOSE ===
print("\n=== Transpose ===")
print(f"Original shape: {farm_factors.shape}")
print(f"Transposed shape: {farm_factors.T.shape}")
print(f"Transposed:\n{farm_factors.T}")

# === ELEMENT-WISE VS MATRIX OPERATIONS ===
print("\n=== Element-wise vs Matrix ===")
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(f"A * B (element-wise):\n{A * B}")
print(f"A @ B (matrix multiply):\n{A @ B}")

# === PRACTICAL: NUTRIENT CALCULATION ===
print("\n=== Fertilizer Mix Calculation ===")
# NPK requirements per crop (kg/ha)
npk_needs = np.array([
    [120, 60, 40],   # Wheat
    [100, 50, 50],   # Rice
    [80, 40, 30]     # Millet
])

# Area of each crop (hectares)
areas = np.array([[5], [3], [2]])  # Column vector

# Total NPK needed = crops × areas
total_npk = npk_needs.T @ areas
print(f"Total N needed: {total_npk[0][0]} kg")
print(f"Total P needed: {total_npk[1][0]} kg")
print(f"Total K needed: {total_npk[2][0]} kg")


=== Matrix Creation ===
Farm Factors (3x4):
[[ 28.  150.    6.5  50. ]
 [ 30.  120.    6.8  45. ]
 [ 26.  180.    6.2  60. ]]

Weights (4x1):
[ 10   5 100  20]

=== Matrix Multiplication ===
Predicted Yields:
[3680. 3480. 3980.]

=== Transpose ===
Original shape: (3, 4)
Transposed shape: (4, 3)
Transposed:
[[ 28.   30.   26. ]
 [150.  120.  180. ]
 [  6.5   6.8   6.2]
 [ 50.   45.   60. ]]

=== Element-wise vs Matrix ===
A * B (element-wise):
[[ 5 12]
 [21 32]]
A @ B (matrix multiply):
[[19 22]
 [43 50]]

=== Fertilizer Mix Calculation ===
Total N needed: 1060 kg
Total P needed: 530 kg
Total K needed: 410 kg
