In [1]:
# Traditional Python list
temps_list = [72, 75, 68, 71, 74, 69, 73]
# Convert to NumPy array
import numpy as np
temps_array = np.array([72, 75, 68, 71, 74, 69, 73])
print(temps_array)
# Output: [72 75 68 71 74 69 73]
print(type(temps_array))
# Output: <class 'numpy.ndarray'>

[72 75 68 71 74 69 73]
<class 'numpy.ndarray'>


In [2]:
# Temperatures from 3 sensors over 5 days
sensor_temps = np.array([
 [72, 70, 71], # Day 1
 [75, 73, 74], # Day 2
 [68, 67, 69], # Day 3
 [71, 70, 72], # Day 4
 [74, 72, 73] # Day 5
])
print(sensor_temps)
print(f"Shape: {sensor_temps.shape}")
# Output: Shape: (5, 3)
# 5 rows (days), 3 columns (sensors)

[[72 70 71]
 [75 73 74]
 [68 67 69]
 [71 70 72]
 [74 72 73]]
Shape: (5, 3)


In [3]:
crops = np.array(['corn', 'wheat', 'soy', 'barley', 'oats'])
# Access single element (zero-indexed)
print(crops[0]) # Output: 'corn'
print(crops[-1]) # Output: 'oats' (negative indexing from end)
# Access multiple elements
print(crops[1:4]) # Output: ['wheat' 'soy' 'barley'] (slice from index 1 to 3)
print(crops[::2]) # Output: ['corn' 'soy' 'oats'] (every 2nd element)

corn
oats
['wheat' 'soy' 'barley']
['corn' 'soy' 'oats']


In [4]:
# Soil pH readings (3 fields × 4 samples)
ph_levels = np.array([
 [6.5, 6.8, 6.3, 6.7],
 [7.1, 7.0, 6.9, 7.2],
 [6.2, 6.4, 6.1, 6.3]
])
# Single element: row 1, column 2
print(ph_levels[1, 2]) # Output: 6.9
# Entire row 0
print(ph_levels[0, :])
# Output: [6.5 6.8 6.3 6.7]
# Entire column 3
print(ph_levels[:, 3])

6.9
[6.5 6.8 6.3 6.7]
[6.7 7.2 6.3]


In [5]:
temperatures = np.array([72, 85, 91, 68, 95, 70, 88])
# Create a boolean array (mask)
hot_days = temperatures > 85
print(hot_days)
# Output: [False False True False True False True]
# Use mask to filter original array
print(temperatures[hot_days])
# Output: [91 95 88]
# Can do it in one line
print(temperatures[temperatures > 85])

[False False  True False  True False  True]
[91 95 88]
[91 95 88]


In [6]:
# Crop yields in tons
field_a = np.array([120, 135, 142, 128])
field_b = np.array([118, 140, 138, 132])
# Add arrays
total_yield = field_a + field_b
print(total_yield)
# Output: [238 275 280 260]
# Subtract to find difference
difference = field_a - field_b
print(difference)
# Output: [2 -5 4 -4]
# Multiply each by a constant
doubled = field_a * 2
print(doubled)
# Output: [240 270 284 256]

[238 275 280 260]
[ 2 -5  4 -4]
[240 270 284 256]


In [10]:
# Base prices for 3 products
base_prices = np.array([[10], [20], [30]]) # 3×1
# Discounts for 4 stores
discounts = np.array([0.9, 0.85, 0.95, 0.88]) # 1×4
# Broadcast multiplication
final_prices = base_prices * discounts
print(final_prices)

[[ 9.   8.5  9.5  8.8]
 [18.  17.  19.  17.6]
 [27.  25.5 28.5 26.4]]
